---

- name: Register distribution repository name (CentOS)
  ansible.builtin.set_fact:
    distrib_repo_name: "rhel{{ ansible_distribution_major_version }}"

- name: Add CUDA repository (CentOS)
  ansible.builtin.get_url:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ distrib_repo_name }}/{{ arch_repo_name }}/cuda-{{ distrib_repo_name }}.repo"
    dest: "/etc/yum.repos.d/cuda.repo"
    mode: '0644'

- name: Install driver dependencies (CentOS)
  ansible.builtin.yum:
    name:
      - "kernel-devel-{{ ansible_kernel }}"
      - "kernel-headers-{{ ansible_kernel }}"

- name: Install driver (CentOS)
  ansible.builtin.yum:
    name:
      - "nvidia-driver-branch-${{ driver_version }}-cuda"
