---

- block:
  - ansible.builtin.import_tasks: "ubuntu.yaml"
    when: "ansible_distribution == 'Ubuntu'"

  - ansible.builtin.import_tasks: "centos.yaml"
    when: "ansible_distribution == 'Centos'"

  - ansible.builtin.import_tasks: "amazon.yaml"
    when: "ansible_distribution == 'Amazon'"

  - name: Register NVIDIA runtime (containerd)
    ansible.builtin.copy:
      src: "containerd-config.toml"
      dest: "/etc/eks/containerd/containerd-config.toml"
      mode: 0644
      owner: root
      group: root
    when: "register_nvidia_runtime is defined and register_nvidia_runtime"

  - name: Register NVIDIA runtime (docker)
    ansible.builtin.copy:
      src: "daemon.json"
      dest: "/etc/docker/daemon.json"
      mode: 0644
      owner: root
      group: root
    when: "register_nvidia_runtime is defined and register_nvidia_runtime"
  when: "gpu_node is defined and gpu_node"
