---

- name: Add NVIDIA Container Toolkit repository key (Ubuntu)
  ansible.builtin.apt_key:
    url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    state: present

- name: Add NVIDIA Container Toolkit repository (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
    state: present

- name: Install NVIDIA Container Toolkit (Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
    name: "nvidia-container-toolkit"
